name: Checks (commit)

on:
  - push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Setup sbt for macos
        if: matrix.os == 'macos-latest'
        run: brew install sbt
      - name: Run tests
        run: sbt test
